spring:
  application:
    name: gis-map
  datasource:
    url: jdbc:postgresql://localhost:5432/gisdb
    username: gisuser
    password: gispassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
        show_sql: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

server:
  port: 8081

geoserver:
  base-url: http://localhost:8080/geoserver
  workspace: gisproject
  username: admin
  password: admin