spring:
  application:
    name: gis-map
  datasource:
    url: jdbc:h2:mem:gisdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: false
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

# Disable GeoServer for H2 testing
geoserver:
  enabled: false